# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Realm of Data Science
# email: pavitrashivananda.prabhu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
   Experienced in data analysis, R and Python with a MS in Finance Analysis and a Bachelor of Electronics and Communication Engineering. Previously a software engineer at Infosys and Société Générale.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  prabhupavitra

# --- Outputting options --- #
# More information can be found on Jekyll's site
timezone: "America/Menominee"
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
paginate: 10
paginate_path: "/page:num/"

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/Untitled.jpeg"


# --- List of links in the navigation bar --- #
navbar-links:
  Projects : "projects"
  Blog : ""
  About Me : "aboutme"

# --- Footer options --- #


# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
# disqus: "yourusername"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Default YAML values (more information on Jekyll's site)  
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      addthis-plugin: true
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
